py_error_boundary
